apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader-service
spec:
  selector:
    matchLabels:
      app: uploader-service
  template:
    metadata:
      labels:
        app: uploader-service
    spec:
      containers:
      - name: uploader-service
        image: arpit0101001/linked-app-uploader-service:latest
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "100m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "k8s"
          - name: SPRING_CLOUD_GCP_STORAGE_BUCKET_NAME
            value: "linkedin_project_microservice"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/secrets/gcp-key.json"
          - name: CLOUD_NAME
            value: "dummy"
          - name: API_KEY
            value: "dummy"
          - name: API_SECRET
            value: "dummy"
        volumeMounts:
          - name: gcp-credentials
            mountPath: /secrets
            readOnly: true
        ports:
        - containerPort: 9050
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
---

apiVersion: v1
kind: Service
metadata:
  name: uploader-service
spec:
  selector:
    app: uploader-service
  ports:
  - port: 80
    targetPort: 9050
